import type { Metadata } from "next";
import {poppins} from "./ui/fonts";

// import "swiper/css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Datnas LMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} text-[40px] antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
