import type { Metadata } from "next";
import { poppins } from "./ui/fonts";
import { AuthProvider } from "./lib/contexts/AuthContext";

import "./globals.css";

export const metadata: Metadata = {
  title: "Datnas LMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} text-[40px] antialiased`}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
